[package]
name = "rust_version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epoll = "4.3.1"
libc = "0.2.140"
thiserror = "1.0.40"
byteorder = "1.4"
chrono = "0.4"
parking_lot = "0.12"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "tcp_server_throughput"
harness = false